### ISSUE TITLE
picture trouble(1)

### ISSUE THREAD

**Issue by aicookie** [aicookie/Five_chess_Akoti#1]
Traceback (most recent call last):
  File "i:\home\yiya\FIVEres_CHESS\game5chess.py", line 150, in <module>
    bg = pygame.image.load("fcb7bf11701da82fa08c033a431872ac.jpeg")
FileNotFoundError: No file 'fcb7bf11701da82fa08c033a431872ac.jpeg' found in working directory

**Comment by aicookie** [comment]
i think it is a big trouble that picture name  is like a #@$!#%&* so python can't find it

**Comment by aicookie** [comment]
i will change the name

**Comment by hyz** [comment]
oh i see the trouble too, you can change the name and see it now

**Comment by aicookie** [comment]
I fix the bug in fe724a1
